// GENERATED by scripts/localized-routes.mjs — do not edit. Edit the
// default-locale page under app/(frontend)/ and re-run the generator.
import type { Metadata } from 'next';
import { MarketingPage } from '@/components/marketing/MarketingPage';
import { buildMetadata } from '@/libs/seo/metadata';
import { DEFAULT_LOCALE, LOCALES, isLocale, type Locale } from '@/libs/i18n/locales';
import { getPage } from '@/modules/marketing/content';

/**
 * Every locale except the default one, which is served unprefixed from the root
 * tree. Listing the default here would publish it twice, at two URLs, with the
 * canonical tag pointing at only one of them.
 */
export function generateStaticParams(): { lang: string }[] {
  return LOCALES.filter((l) => l !== DEFAULT_LOCALE).map((lang) => ({ lang }));
}

/** Narrow the raw segment once, here, so nothing downstream takes a bare string. */
async function localeOf(params: Promise<{ lang: string }>): Promise<Locale> {
  const { lang } = await params;
  return isLocale(lang) ? lang : DEFAULT_LOCALE;
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lang: string }>;
}): Promise<Metadata> {
  return buildMetadata(await localeOf(params), 'help');
}

export default async function Page({ params }: { params: Promise<{ lang: string }> }) {
  return <MarketingPage page={getPage(await localeOf(params), 'help')} />;
}
