// GENERATED by scripts/localized-routes.mjs — do not edit. Edit the
// default-locale image under app/(frontend)/ and re-run the generator.
import { renderOgImage, size, contentType, alt } from '@/libs/seo/og-image';
import { DEFAULT_LOCALE, LOCALES, isLocale } from '@/libs/i18n/locales';

export { size, contentType, alt };

/**
 * Every locale except the default one, which is served unprefixed from the root
 * tree. Listing the default here would publish it twice, at two URLs, with the
 * canonical tag pointing at only one of them.
 */
export function generateStaticParams(): { lang: string }[] {
  return LOCALES.filter((l) => l !== DEFAULT_LOCALE).map((lang) => ({ lang }));
}

export default async function Image({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params;
  return renderOgImage(isLocale(lang) ? lang : DEFAULT_LOCALE, 'legalTerms');
}
