/**
 * Generates `app/(localized)/[lang]/**` from `app/(frontend)/**`, and verifies
 * the two stay identical.
 *
 * ## Why this is generated rather than written
 *
 * A static export cannot negotiate a locale at request time, so every localized
 * URL has to exist as a real file. That means the prefixed tree is a
 * route-for-route mirror of the unprefixed one: twenty pages and twenty
 * Open-Graph images whose only difference is where the locale comes from
 * (`DEFAULT_LOCALE` in the root tree, the `[lang]` segment here).
 *
 * Forty hand-copied files is not a maintenance problem on the day they are
 * written — it is one on the day someone adds route twenty-one and remembers
 * only the tree they were looking at. The prefixed locale would then 404 on a
 * route the site's own sitemap advertises, and nothing would say so. So the
 * mirror is derived, and `--check` fails the build when it drifts.
 *
 * ## What it does NOT generate
 *
 * `app/(localized)/[lang]/layout.tsx`. That file is a root layout with its own
 * `<html lang>`, an untranslated-content notice and the locale threaded into the
 * header and footer; it is genuinely different from the default-locale shell
 * rather than a mechanical rewrite of it, so it is written by hand and left
 * alone here.
 *
 *   node scripts/localized-routes.mjs           # write the mirror
 *   node scripts/localized-routes.mjs --check   # verify it, exit 1 on drift
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';

const root = join(dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
const SRC = join(root, 'app', '(frontend)');
const OUT = join(root, 'app', '(localized)', '[lang]');
const CHECK = process.argv.includes('--check');

/** Pull the RouteKey out of a source file — it is the second argument, always a literal. */
function routeKeyOf(text, fn) {
  const m = new RegExp(`${fn}\\(\\s*DEFAULT_LOCALE\\s*,\\s*'([A-Za-z]+)'`).exec(text);
  return m?.[1] ?? null;
}

function walk(dir, acc = []) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) walk(p, acc);
    else if (e.name === 'page.tsx' || e.name === 'opengraph-image.tsx') acc.push(p);
  }
  return acc;
}

const PARAMS = `/**
 * Every locale except the default one, which is served unprefixed from the root
 * tree. Listing the default here would publish it twice, at two URLs, with the
 * canonical tag pointing at only one of them.
 */
export function generateStaticParams(): { lang: string }[] {
  return LOCALES.filter((l) => l !== DEFAULT_LOCALE).map((lang) => ({ lang }));
}`;

function pageSource(key) {
  return `// GENERATED by scripts/localized-routes.mjs — do not edit. Edit the
// default-locale page under app/(frontend)/ and re-run the generator.
import type { Metadata } from 'next';
import { MarketingPage } from '@/components/marketing/MarketingPage';
import { buildMetadata } from '@/libs/seo/metadata';
import { DEFAULT_LOCALE, LOCALES, isLocale, type Locale } from '@/libs/i18n/locales';
import { getPage } from '@/modules/marketing/content';

${PARAMS}

/** Narrow the raw segment once, here, so nothing downstream takes a bare string. */
async function localeOf(params: Promise<{ lang: string }>): Promise<Locale> {
  const { lang } = await params;
  return isLocale(lang) ? lang : DEFAULT_LOCALE;
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lang: string }>;
}): Promise<Metadata> {
  return buildMetadata(await localeOf(params), '${key}');
}

export default async function Page({ params }: { params: Promise<{ lang: string }> }) {
  return <MarketingPage page={getPage(await localeOf(params), '${key}')} />;
}
`;
}

function ogSource(key) {
  return `// GENERATED by scripts/localized-routes.mjs — do not edit. Edit the
// default-locale image under app/(frontend)/ and re-run the generator.
import { renderOgImage, size, contentType, alt } from '@/libs/seo/og-image';
import { DEFAULT_LOCALE, LOCALES, isLocale } from '@/libs/i18n/locales';

export { size, contentType, alt };

${PARAMS}

export default async function Image({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params;
  return renderOgImage(isLocale(lang) ? lang : DEFAULT_LOCALE, '${key}');
}
`;
}

const wanted = new Map();
for (const file of walk(SRC)) {
  const text = readFileSync(file, 'utf8');
  const isOg = file.endsWith('opengraph-image.tsx');
  const key = routeKeyOf(text, isOg ? 'renderOgImage' : 'buildMetadata');
  if (!key) {
    console.error(`✗ ${relative(root, file)}: could not find its RouteKey — the generator reads it from the DEFAULT_LOCALE call.`);
    process.exit(1);
  }
  wanted.set(join(OUT, relative(SRC, file)), isOg ? ogSource(key) : pageSource(key));
}

if (CHECK) {
  const problems = [];
  for (const [path, body] of wanted) {
    if (!existsSync(path)) problems.push(`missing: ${relative(root, path)}`);
    else if (readFileSync(path, 'utf8').replace(/\r\n/g, '\n') !== body) {
      problems.push(`stale:   ${relative(root, path)}`);
    }
  }
  // A file the mirror no longer wants is drift too: a route deleted from the
  // root tree must not keep answering under a locale prefix.
  if (existsSync(OUT)) {
    for (const file of walk(OUT)) {
      if (!wanted.has(file)) problems.push(`orphan:  ${relative(root, file)}`);
    }
  }
  if (problems.length) {
    console.error('✗ localized route mirror is out of date:');
    for (const p of problems) console.error(`    ${p}`);
    console.error('\n  Run: node scripts/localized-routes.mjs');
    process.exit(1);
  }
  console.log(`✓ ${wanted.size} localized route file(s) match the default-locale tree.`);
  process.exit(0);
}

for (const [path, body] of wanted) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body, 'utf8');
}
if (existsSync(OUT)) {
  for (const file of walk(OUT)) {
    if (!wanted.has(file)) {
      rmSync(file);
      console.log(`removed orphan ${relative(root, file)}`);
    }
  }
}
console.log(`wrote ${wanted.size} file(s) under app/(localized)/[lang]/`);
